# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/ko

# Uncomment the lines below to configure your website in a second language.
# ko:
#  languageCode: en-us
#  contentDir: content
#  menu:
#    main:
#      - name: Bio
#        url: /
#        weight: 10
#      - name: Experience
#        url: /#experience
#        weight: 20
#      - name: Projects
#        url: project/
#        weight: 30
#      - name: Publications
#        url: publication/
#        weight: 40
#      - name: +
#        url: additional/
#        weight: 50
