# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: ./#about
    weight: 10
  - name: Experience
    url: ./#experience
    weight: 20
  - name: Projects
    url: ./#projects
    weight: 30
  - name: Publications
    url: publication/
    weight: 40
  - name: 🏆
    identifier: add
    url: additional/
    weight: 50
  - name: Awards
    parent: add
    url: additional/#awards
    weight: 50
  - name: Certifications
    parent: add
    url: additional/#certs
    weight: 50
